### ISSUE TITLE
GestureEventType Never Clears

### ISSUE THREAD

**Issue by HUGEwindow** [openspatial/Unity#1]
In using the unity SDK Gesture events never seem to clear. Gesture events continuously fire leaving the last gesture to fire until a direction change. Any suggestions?

**Comment by nodpaw9000** [comment]
What system are you targeting? {PC, iOS, Android }
Can you send me a boiled down example script demonstrating this?
Look at Assets\Nod\Examples\Scripts\Example2.cs for an example of how to use gestures.
After calling ring.CheckForUpdate(), ring.gestureState will reflect the last gesture received until you call CheckForUpdate again.  In this way gestures should only be valid for the frame they get fired.  The system specific plugin is supposed to clear the flag after CheckForUpdate gets called.  If its not let me know and we will look into it.

**Comment by HUGEwindow** [comment]
Thank you for the quick reply (I am using Example2.cs on osx). My issue is that ring.CheckForUpdate() is being called on every frame to check the status of the ring (this works for realtime direction changes), but not specific gestures as last gesture fires on every frame.  

void OnGUI()
    {

```
        if(ring.gestureState == GestureEventType.SWIPE_RIGHT){
            Debug.Log( mostRecentGesture.ToString());
                       ///will fire endless fire on every frame until new gestureState
                    }

}
```

**Comment by nodpaw9000** [comment]
OSX Unity support got dropped, for now, we may support it in the future.  We do support iOS.  The dev that added mac support based his code off of the iOS code, I'm told he didn't have to change any code to get it to work.  So there might be a way that you could produce a new bundle for mac based off the iOS code to get a bundle that works.

**Comment by HUGEwindow** [comment]
Mac OS X & iOS work fine. I am not sure how to produce a bundle. Any suggestions?

**Comment by HUGEwindow** [comment]
Does the windows unity version have this same issue?

**Comment by Khwaab** [comment]
In our windows unity plugin and all our demo's and examples associated with
it we only see gestures firing once. We have currently suspended support
for unity on OS X and our general OS X integration is in a very early beta
stage. Developments on the OS X SDK's and plugins will happen within the
next few months, so keep a look out for any updates.

Windows, Android and iOS are currently supported and we do not observe the
repeated gestures on any of those platforms using the Nod SDK examples.

Thanks,
Khwaab Dave

**Comment by HUGEwindow** [comment]
Khwaab,

I have created a solid interaction prototype with your OSX SDK.  I am currently creating one for Unity / Oculus.  Unfortunately,  I am developing on OSX.  I am not sure what the level of effort would be to fix this issue, I appreciate your responses and all of the SDKS available. 

Thanks
Matthew

**Comment by nodpaw9000** [comment]
You could code around it on your side by doing the same thing we do internally for the other OS specific implimentaitons.  Which is to reset the gesture state to None after you read its value.  OSX support currently isn't on the table for us.  Seems like things happen to work for you which is great but we don't have anyone testing that platform so we wont be able to comment of the stability of the rest of the api entry points.  We would like to officially support OSX in the future but we do not currently have a time line for that.

**Comment by HUGEwindow** [comment]
I tried to set the to .None and it gets overwritten. Thanks.

**Comment by Khwaab** [comment]
Hi,

Please replace the NodPlugin.bundle in the Assets/Plugins folder in the
unity project with the attached bundle. Please let me know if that fixes
your problem.

Khwaab Dave
​​

**Comment by HUGEwindow** [comment]
Khwaab,

Thank your the reply, Am I missing the attachment? Can't wait to give it a shot. Thanks!

**Comment by Khwaab** [comment]
I see the attachment. Maybe attachments don't work through github emails.

What is your email? I can email it to you directly.

**Comment by HUGEwindow** [comment]
open@hugewindow.com

**Comment by HUGEwindow** [comment]
Thanks for your Help & support. Truly appreciate it. 

Matthew

**Comment by Khwaab** [comment]
No worries, did the new bundle work for you?

**Comment by HUGEwindow** [comment]
Sure did. Thank you! I sent an email earlier but server kept bunting back, I really appreciate it.  Can't wait to integrate into my unity app. Thanks again.  Nod is great.
